services:
  db:
    image: postgres:15-alpine
    container_name: waste_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waste_db
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    container_name: waste_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8321:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/waste_db
    depends_on:
      - db
    restart: always

  parser:
    build: .
    container_name: waste_parser
    command: python -m app.infrastructure.telegram.tg_parser
    environment:
      - API_WEBHOOK_URL=http://api:8000/api/sensors/webhook
    depends_on:
      - api
    restart: always