"""add scan_logs table

Revision ID: b0521f98e336
Revises: 0c5b7630f966
Create Date: 2026-03-28 11:10:33.454714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0521f98e336'
down_revision: Union[str, Sequence[str], None] = '0c5b7630f966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('fill_percent', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_container_id'), 'scan_logs', ['container_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_logs_container_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    # ### end Alembic commands ###
